---
title: "Lazy Loading of Shiny Apps"
author: "Daniel Kaplan"
date: "3/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Some empty space

<iframe loading="lazy" width="740" height="515" src="https://dtkaplan.shinyapps.io/lazy-load-questions/#2" frameborder="2" allowfullscreen></iframe>



When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

## More empty space


When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

## More empty space

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...
## More empty space


When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...
## More empty space


When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...
## More empty space


When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...
## More empty space


When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...
## More empty space


When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...
## More empty space


When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...
## More empty space


When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...

When in the course ...




## Finally, an App

When in the course ...


<iframe loading="lazy" width="560" height="315" src="https://maa-statprep.shinyapps.io/Little_App_Regression/" frameborder="0" allowfullscreen></iframe>

